### ISSUE TITLE
希望增加midi转mider code的功能

### ISSUE THREAD

**Issue by PoTaTo625** [whiterasbk/MiraiMidiProduce#8]
如题

**Comment by whiterasbk** [comment]
计划中（

**Comment by whiterasbk** [comment]
@PoTaTo625  有需求的话可以关注一下这个项目 [midi2midercode](https://github.com/ShadowStudioOrganization/Midi2Midercode), 但是用复杂的midi生成的 midercode 效果目前来说不是很好

**Comment by PoTaTo625** [comment]
！感谢~
