### ISSUE TITLE
希望另外单独提供一个程序实现传入指令生成音频文件

### ISSUE THREAD

**Issue by Vescrity** [whiterasbk/MiraiMidiProduce#9]
您好！如果您有时间的话，我希望有一个程序能够单独实现这个功能（如题）。因为我使用了另外一套程序来运行qq机器人，并不能实现直接使用这些插件，而我想通过其他方法使用这个功能。比如通过http来发送请求并传递指令，然后能够获取到生成的音频文件（名）。如果您有时间能够进行相关开发的话，感激不尽！
希望没有给您添麻烦，祝好！

**Comment by whiterasbk** [comment]
MidiProduce 解析 midercode 使用的是 [mider](https://github.com/whiterasbk/mider) 
如果想自己实现可以参考一下这个项目, 我近期或将增加一个通过 http 调用 此功能的子项目

**Comment by whiterasbk** [comment]
@Vescrity 最新版的 release 已提供相关功能
下载 mider-produce-service-all.jar 并使用 java -jar 命令就可以启动一个生成音频的 produce 服务
入口是 `post` `hostname:8080/api`
body 是 一个包含 `midercode` 字段的 json
